"""GPU lease runtime — lease-decorated SDK stage calls, duration estimators,
per-request state reset, and the startup AOTI compilation probe."""
import time

from config import get_vad_duration, get_asr_duration, ZEROGPU_MAX_DURATION
from qua_sdk.schemas import Audio, Region, Regions
from src.pipeline.fastconformer_onnx import transcribe_fastconformer_onnx_with_logprobs
from src.pipeline.arabic_matching import normalize_arabic

def _reset_request_state():
    pass

def _capture_vram_safely():
    return 0.0, 0.0


def run_vad_and_asr_gpu(audio, sample_rate, model_name="Base", fast_mode=False):
    """Single CPU run: Custom overlap inference + FastConformer recognition.
    
    Bypasses VAD entirely to process audio continuously in 30-second
    overlapping chunks, eliminating mid-word cuts and lost silences.
    """
    # Import internal SDK schemas required to format the output.
    from qua_sdk.schemas import Emissions, Region, Regions
    
    # Track the start time of the entire processing lease.
    t_lease_start = time.time()
    
    # Define the duration of each acoustic window chunk (30 seconds).
    chunk_dur = 30.0
    
    # Determine how far to advance the window each step (stride).
    # Fast mode uses a larger stride (25s) with a smaller overlap (5s) for speed.
    # Normal mode uses a smaller stride (20s) with a larger overlap (10s) for robust context.
    step_dur = 25.0 if fast_mode else 20.0
    
    # Calculate the total duration of the audio in seconds based on the array length and sample rate.
    audio_dur = len(audio) / sample_rate
    
    # List to store the exact timing boundaries of each accepted audio segment.
    regions_list = []
    
    # Start tracking the time specifically spent on ASR inference.
    t_asr_start = time.time()
    
    # List to store the text tokens generated by the model (used for DP matching).
    tokens = []
    
    # List to track raw text strings and timestamps for debugging (saved to raw_transcription.json).
    raw_transcriptions = []
    
    # List to store the raw CTC log probability matrices for forced alignment later.
    logprobs_list = []
    
    # Generate the start times for all chunks across the entire audio.
    chunk_starts = []
    t = 0.0
    while t < audio_dur:
        chunk_starts.append(t)
        t += step_dur
        
    # Iterate through every generated chunk start time.
    for i, start_s in enumerate(chunk_starts):
        # Calculate the absolute end time of the current chunk, capped at the total audio duration.
        end_s = min(start_s + chunk_dur, audio_dur)
        
        # Convert absolute seconds into array indices using the sample rate.
        start_idx = int(start_s * sample_rate)
        end_idx = int(end_s * sample_rate)
        
        # Slice the audio array to extract the acoustic data for this specific window.
        seg_audio = audio[start_idx:end_idx]
        
        # Run the FastConformer ONNX model on the extracted audio chunk.
        # This returns the recognized text, the timing for each word, and the raw CTC probabilities.
        text, word_timestamps, logprobs = transcribe_fastconformer_onnx_with_logprobs(seg_audio, fast_mode=fast_mode)
        
        # Calculate the exact mathematical overlap duration between consecutive chunks.
        overlap = chunk_dur - step_dur
        
        # The cut margin defines the exact center of the overlap to ensure seamless splicing.
        cut_margin = overlap / 2.0
        
        # List to store words that survive the boundary cutoff rules.
        filtered_words = []
        for w in word_timestamps:
            # Get the relative start time of the word within the current 30-second chunk.
            rel_start = w['start']
            
            # Mathematical rules to keep words roughly in the center of the chunk and drop words near the overlapping edges.
            # This completely prevents duplicated or fragmented words at the chunk boundaries.
            if i == 0:
                # For the very first chunk, keep everything from the start up until the trailing overlap cutoff.
                keep = (rel_start < chunk_dur - cut_margin)
            elif i == len(chunk_starts) - 1:
                # For the very last chunk, keep everything after the leading overlap cutoff until the end.
                keep = (rel_start >= cut_margin)
            else:
                # For all middle chunks, keep words strictly within the safe central bounds.
                keep = (cut_margin <= rel_start < chunk_dur - cut_margin)
                
            # If the word falls within the safe bounds, append it to the filtered list.
            if keep:
                filtered_words.append(w)
                
        # If no words survived the filtering (e.g., complete silence in the safe zone), skip this chunk.
        if not filtered_words:
            continue
            
        # Reconstruct the text for this chunk using only the safe, filtered words.
        chunk_text = " ".join([w['word'] for w in filtered_words])
        
        # Calculate the absolute start and end times for this specific text block in the global audio track.
        abs_start_time = start_s + filtered_words[0]['start']
        abs_end_time = start_s + filtered_words[-1]['end']
        
        # Register the valid region boundary for the global pipeline.
        regions_list.append(Region(start_s=abs_start_time, end_s=abs_end_time))
        
        # Store the raw, unedited transcription data for debugging and external usage.
        raw_transcriptions.append({
            "segment": len(raw_transcriptions) + 1,
            "start_time": abs_start_time,
            "end_time": abs_end_time,
            "text": chunk_text
        })
        
        # Normalize the text by removing diacritics and standardizing characters.
        norm_text = normalize_arabic(chunk_text)
        
        # Break the text into a list of individual characters, appending a space at the end.
        # This character-level splitting is critical to allow the DP matcher to bypass FastConformer's word-spacing errors.
        tokens.append(list(norm_text) + [' '])
        
        # Store the CTC probability matrix for this chunk so the force aligner can extract letter timings later.
        logprobs_list.append(logprobs)
        
    # Wrap the processed regions into the SDK's Regions schema object.
    regions = Regions(regions=regions_list, audio_duration_s=audio_dur)
    
    # Wrap the character tokens into the SDK's Emissions schema object.
    emissions = Emissions(tokens=tokens)
    
    # Open the raw_transcription.json file to save the unfiltered sliding window output.
    import json
    with open("raw_transcription.json", "w", encoding="utf-8") as f:
        # Dump the raw transcriptions as a formatted JSON file with UTF-8 support.
        json.dump({"transcriptions": raw_transcriptions}, f, ensure_ascii=False, indent=2)
        
    # Since VAD was entirely bypassed, the dedicated VAD GPU time is hardcoded to 0.0 seconds.
    vad_gpu_time = 0.0
    
    # Calculate the total execution time spent running the ASR chunks.
    asr_gpu_time = time.time() - t_asr_start
    
    # Construct an empty stage metrics dictionary (required by legacy SDK downstream systems) and embed the logprobs.
    stage_metrics = {"segmentation": {}, "recognition": {}, "logprobs": logprobs_list}
    
    # Return the aggregated outputs matching the legacy tuple structure required by the SDK.
    return (regions, emissions, stage_metrics,
            vad_gpu_time, asr_gpu_time, 0.0, 0.0)


def run_phoneme_asr_gpu(audio, sample_rate, intervals, model_name="Base"):
    """Standalone recognition CPU.

    Returns (emissions, rec_metrics, asr_gpu_time, peak_vram, reserved_vram).
    """
    audio_obj = Audio.from_array(audio, sample_rate)
    regions = Regions(
        regions=[Region(start_s=float(s), end_s=float(e)) for s, e in intervals],
        audio_duration_s=len(audio) / sample_rate,
    )

    t_asr_start = time.time()
    from qua_sdk.schemas import Emissions
    tokens = []
    raw_transcriptions = []
    
    # Process each segmented region using FastConformer CPU
    for reg in regions.regions:
        start_idx = int(reg.start_s * sample_rate)
        end_idx = int(reg.end_s * sample_rate)
        seg_audio = audio[start_idx:end_idx]
        
        text, word_timestamps, logprobs = transcribe_fastconformer_onnx_with_logprobs(seg_audio)
        raw_transcriptions.append({
            "segment": len(raw_transcriptions) + 1,
            "start_time": reg.start_s,
            "end_time": reg.end_s,
            "text": text
        })
        text = normalize_arabic(text)
        tokens.append(list(text) + [' '])
        
    import json
    with open("raw_transcription.json", "w", encoding="utf-8") as f:
        json.dump({"transcriptions": raw_transcriptions}, f, ensure_ascii=False, indent=2)
        
    emissions = Emissions(tokens=tokens)
    asr_gpu_time = time.time() - t_asr_start
    rec_metrics = {}

    peak_vram, reserved_vram = _capture_vram_safely()

    return emissions, rec_metrics, asr_gpu_time, peak_vram, reserved_vram

